---
# defaults file for witcom.traefik_docker

traefik_instance_name: internal

traefik_dir: "/etc/traefik"

#env_vars

traefik_env: {}

traefik_certificatesResolvers: {}

traefik_image: "docker.io/library/traefik:v2.7"

traefik_log_level: ERROR

traefik_network: traefik

traefik_state: "present"
traefik_recreate: "no"

_file_provider_dir: "{{ traefik_dir }}/file-provider-config"
_acme_dir: "{{ traefik_dir }}/acme"
