---
- name: Deploy Traefik-Container
  vars:
    traefik_container_name: "{{ inventory_hostname_short }}.traefik_{{ traefik_instance_name }}"
  block:

    - name: Gather info about specific network
      containers.podman.podman_network_info:
        name: "{{ traefik_network }}"
      register: network_result
      ignore_errors: True

    - name: Create network for traefik if it does not exist
      containers.podman.podman_network:
        name: "{{ traefik_network }}"
        state: "present"
        recreate: "no"
      when: network_result.failed

    - name: Run traefik container
      containers.podman.podman_container:
        name: "{{ traefik_container_name }}"
        image: "{{ traefik_image }}"
        state: "{{ traefik_state }}"
        user: root
        recreate: "{{ traefik_recreate }}"
        network: "{{ traefik_network }}"
        publish:
          -  "80:80"
          -  "443:443"
        label:
          process=traefik
        generate_systemd:
          path: /etc/systemd/system
          separator: "-"
          container_prefix: "container"
        memory: "{{ traefik_memory_limit | default('1g') | human_to_bytes }}"
        memory_swap: "{{ traefik_memory_limit | default('1g') | human_to_bytes * 2 }}"
        cpu_period: "{{ traefik_cpu_limit | default(1) | int * 100000 }}"        
        env: "{{ traefik_env }}"
        volume:
          - "{{ traefik_dir }}:/etc/traefik:z"
      register: result
      until: result is success
      retries: 3
      delay: 5
      notify: enable-podman-systemd-service

